// SPDX-License-Identifier: Apache-2.0
//
// The gateway↔agentd wire protocol (docs/AGENT-ARCHITECTURE.md, Horizon B).
// The CONTROL PLANE is the single gRPC server; agentd is a pure client that
// dials in (no listener on engine hosts, NAT-friendly). Control→agent
// commands flow as correlated request/response envelopes over one persistent
// bidirectional Session stream. Bulk artifact bytes never ride the session:
// the agent pulls them back over FetchArtifact on a separate HTTP/2 stream
// of the same connection.
//
// Compatibility rules: field numbers are forever; new verbs/payloads are
// additive oneof cases; an agent answering an unknown verb sets
// CommandResult.unsupported. This protocol is the product boundary for the
// managed-deployments layer — evolve it like a public API.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agentwire/agent.proto

package agentwire

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Session_FullMethodName       = "/openexchange.agent.v1.ControlPlane/Session"
	ControlPlane_FetchArtifact_FullMethodName = "/openexchange.agent.v1.ControlPlane/FetchArtifact"
	ControlPlane_Enroll_FullMethodName        = "/openexchange.agent.v1.ControlPlane/Enroll"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	// One persistent session per agent. First agent message MUST be Hello;
	// the control plane answers HelloAck, then the agent sends a full
	// StateSnapshot, replays buffered events, and serves commands.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error)
	// Agent-initiated pull of artifact bytes referenced by an InstallArtifact
	// command (chunked; separate HTTP/2 stream, no head-of-line blocking).
	FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error)
	// Milestone 4+: join-token -> embedded-CA-issued client certificate.
	// Declared now to freeze the wire surface; returns UNIMPLEMENTED.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SessionClient = grpc.BidiStreamingClient[AgentMessage, ControlMessage]

func (c *controlPlaneClient) FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_FetchArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchArtifactRequest, ArtifactChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_FetchArtifactClient = grpc.ServerStreamingClient[ArtifactChunk]

func (c *controlPlaneClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	// One persistent session per agent. First agent message MUST be Hello;
	// the control plane answers HelloAck, then the agent sends a full
	// StateSnapshot, replays buffered events, and serves commands.
	Session(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error
	// Agent-initiated pull of artifact bytes referenced by an InstallArtifact
	// command (chunked; separate HTTP/2 stream, no head-of-line blocking).
	FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error
	// Milestone 4+: join-token -> embedded-CA-issued client certificate.
	// Declared now to freeze the wire surface; returns UNIMPLEMENTED.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Session(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedControlPlaneServer) FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error {
	return status.Errorf(codes.Unimplemented, "method FetchArtifact not implemented")
}
func (UnimplementedControlPlaneServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).Session(&grpc.GenericServerStream[AgentMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SessionServer = grpc.BidiStreamingServer[AgentMessage, ControlMessage]

func _ControlPlane_FetchArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).FetchArtifact(m, &grpc.GenericServerStream[FetchArtifactRequest, ArtifactChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_FetchArtifactServer = grpc.ServerStreamingServer[ArtifactChunk]

func _ControlPlane_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openexchange.agent.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _ControlPlane_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _ControlPlane_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchArtifact",
			Handler:       _ControlPlane_FetchArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agentwire/agent.proto",
}
