// SPDX-License-Identifier: Apache-2.0
//
// The gateway↔agentd wire protocol (docs/AGENT-ARCHITECTURE.md, Horizon B).
// The CONTROL PLANE is the single gRPC server; agentd is a pure client that
// dials in (no listener on engine hosts, NAT-friendly). Control→agent
// commands flow as correlated request/response envelopes over one persistent
// bidirectional Session stream. Bulk artifact bytes never ride the session:
// the agent pulls them back over FetchArtifact on a separate HTTP/2 stream
// of the same connection.
//
// Compatibility rules: field numbers are forever; new verbs/payloads are
// additive oneof cases; an agent answering an unknown verb sets
// CommandResult.unsupported. This protocol is the product boundary for the
// managed-deployments layer — evolve it like a public API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agentwire/agent.proto

package agentwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulkRequest_Op int32

const (
	BulkRequest_OP_UNSPECIFIED BulkRequest_Op = 0
	BulkRequest_START_ALL      BulkRequest_Op = 1
	BulkRequest_STOP_ALL       BulkRequest_Op = 2
	BulkRequest_RESTART_ALL    BulkRequest_Op = 3
)

// Enum value maps for BulkRequest_Op.
var (
	BulkRequest_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "START_ALL",
		2: "STOP_ALL",
		3: "RESTART_ALL",
	}
	BulkRequest_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"START_ALL":      1,
		"STOP_ALL":       2,
		"RESTART_ALL":    3,
	}
)

func (x BulkRequest_Op) Enum() *BulkRequest_Op {
	p := new(BulkRequest_Op)
	*p = x
	return p
}

func (x BulkRequest_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BulkRequest_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_agentwire_agent_proto_enumTypes[0].Descriptor()
}

func (BulkRequest_Op) Type() protoreflect.EnumType {
	return &file_agentwire_agent_proto_enumTypes[0]
}

func (x BulkRequest_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BulkRequest_Op.Descriptor instead.
func (BulkRequest_Op) EnumDescriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{12, 0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Snapshot
	//	*AgentMessage_Result
	//	*AgentMessage_Event
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agentwire_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Snapshot struct {
	Snapshot *StateSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type AgentMessage_Event struct {
	Event *Event `protobuf:"bytes,4,opt,name=event,proto3,oneof"` // unsolicited lifecycle events
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Snapshot) isAgentMessage_Msg() {}

func (*AgentMessage_Result) isAgentMessage_Msg() {}

func (*AgentMessage_Event) isAgentMessage_Msg() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlMessage_HelloAck
	//	*ControlMessage_Command
	Msg           isControlMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agentwire_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetMsg() isControlMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Msg.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isControlMessage_Msg interface {
	isControlMessage_Msg()
}

type ControlMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"` // 3 reserved: DesiredState document (milestone 4)
}

func (*ControlMessage_HelloAck) isControlMessage_Msg() {}

func (*ControlMessage_Command) isControlMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtoVersion  uint32                 `protobuf:"varint,3,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"` // bump on incompatible envelope changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agentwire_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // when rejected (version mismatch, duplicate host displaced, ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_agentwire_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelloAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Full process-state snapshot, sent after Hello and on control-plane request.
type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_agentwire_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StateSnapshot) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // correlation id, unique per session
	// Types that are valid to be assigned to Verb:
	//
	//	*Command_List
	//	*Command_Get
	//	*Command_Summary
	//	*Command_Start
	//	*Command_Stop
	//	*Command_Restart
	//	*Command_Bulk
	//	*Command_TailLog
	//	*Command_NodeCounters
	//	*Command_Install
	Verb          isCommand_Verb `protobuf_oneof:"verb"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agentwire_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetVerb() isCommand_Verb {
	if x != nil {
		return x.Verb
	}
	return nil
}

func (x *Command) GetList() *ListRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Command) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Command) GetSummary() *SummaryRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *Command) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Command) GetStop() *StopRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetRestart() *RestartRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *Command) GetBulk() *BulkRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Bulk); ok {
			return x.Bulk
		}
	}
	return nil
}

func (x *Command) GetTailLog() *TailLogRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_TailLog); ok {
			return x.TailLog
		}
	}
	return nil
}

func (x *Command) GetNodeCounters() *NodeCountersRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_NodeCounters); ok {
			return x.NodeCounters
		}
	}
	return nil
}

func (x *Command) GetInstall() *InstallArtifactRequest {
	if x != nil {
		if x, ok := x.Verb.(*Command_Install); ok {
			return x.Install
		}
	}
	return nil
}

type isCommand_Verb interface {
	isCommand_Verb()
}

type Command_List struct {
	List *ListRequest `protobuf:"bytes,10,opt,name=list,proto3,oneof"`
}

type Command_Get struct {
	Get *GetRequest `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type Command_Summary struct {
	Summary *SummaryRequest `protobuf:"bytes,12,opt,name=summary,proto3,oneof"`
}

type Command_Start struct {
	Start *StartRequest `protobuf:"bytes,13,opt,name=start,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopRequest `protobuf:"bytes,14,opt,name=stop,proto3,oneof"`
}

type Command_Restart struct {
	Restart *RestartRequest `protobuf:"bytes,15,opt,name=restart,proto3,oneof"`
}

type Command_Bulk struct {
	Bulk *BulkRequest `protobuf:"bytes,16,opt,name=bulk,proto3,oneof"`
}

type Command_TailLog struct {
	TailLog *TailLogRequest `protobuf:"bytes,17,opt,name=tail_log,json=tailLog,proto3,oneof"`
}

type Command_NodeCounters struct {
	NodeCounters *NodeCountersRequest `protobuf:"bytes,18,opt,name=node_counters,json=nodeCounters,proto3,oneof"`
}

type Command_Install struct {
	Install *InstallArtifactRequest `protobuf:"bytes,19,opt,name=install,proto3,oneof"`
}

func (*Command_List) isCommand_Verb() {}

func (*Command_Get) isCommand_Verb() {}

func (*Command_Summary) isCommand_Verb() {}

func (*Command_Start) isCommand_Verb() {}

func (*Command_Stop) isCommand_Verb() {}

func (*Command_Restart) isCommand_Verb() {}

func (*Command_Bulk) isCommand_Verb() {}

func (*Command_TailLog) isCommand_Verb() {}

func (*Command_NodeCounters) isCommand_Verb() {}

func (*Command_Install) isCommand_Verb() {}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{6}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{8}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unchecked     bool                   `protobuf:"varint,2,opt,name=unchecked,proto3" json:"unchecked,omitempty"` // StartUnchecked: caller sequenced the dependencies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartRequest) GetUnchecked() bool {
	if x != nil {
		return x.Unchecked
	}
	return false
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // ForceStop: bypass reverse-dependency check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RestartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            BulkRequest_Op         `protobuf:"varint,1,opt,name=op,proto3,enum=openexchange.agent.v1.BulkRequest_Op" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRequest) Reset() {
	*x = BulkRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequest) ProtoMessage() {}

func (x *BulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequest.ProtoReflect.Descriptor instead.
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{12}
}

func (x *BulkRequest) GetOp() BulkRequest_Op {
	if x != nil {
		return x.Op
	}
	return BulkRequest_OP_UNSPECIFIED
}

type TailLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogRequest) Reset() {
	*x = TailLogRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogRequest) ProtoMessage() {}

func (x *TailLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogRequest.ProtoReflect.Descriptor instead.
func (*TailLogRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TailLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TailLogRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type NodeCountersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCountersRequest) Reset() {
	*x = NodeCountersRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCountersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCountersRequest) ProtoMessage() {}

func (x *NodeCountersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCountersRequest.ProtoReflect.Descriptor instead.
func (*NodeCountersRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{14}
}

func (x *NodeCountersRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// The artifact bytes are NOT here: the agent calls FetchArtifact(transfer_id)
// back on the same connection and streams them into its local temp-file →
// sha-verify → atomic-rename install.
type InstallArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // single-use handle registered control-plane-side
	DestPath      string                 `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"` // hex; empty skips verification (discouraged)
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`    // unix permission bits; 0 = default 0644
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`    // advisory, for progress reporting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallArtifactRequest) Reset() {
	*x = InstallArtifactRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallArtifactRequest) ProtoMessage() {}

func (x *InstallArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallArtifactRequest.ProtoReflect.Descriptor instead.
func (*InstallArtifactRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InstallArtifactRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *InstallArtifactRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *InstallArtifactRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *InstallArtifactRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *InstallArtifactRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CommandResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                   // matches Command.id
	Error       string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`              // empty = success
	Unsupported bool                   `protobuf:"varint,3,opt,name=unsupported,proto3" json:"unsupported,omitempty"` // agent did not recognize the verb (older agent)
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandResult_List
	//	*CommandResult_Get
	//	*CommandResult_Summary
	//	*CommandResult_Results
	//	*CommandResult_Log
	//	*CommandResult_Counters
	Payload       isCommandResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agentwire_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CommandResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetUnsupported() bool {
	if x != nil {
		return x.Unsupported
	}
	return false
}

func (x *CommandResult) GetPayload() isCommandResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandResult) GetList() *ProcessList {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CommandResult) GetGet() *GetResponse {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *CommandResult) GetSummary() *Summary {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *CommandResult) GetResults() *ActionResults {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_Results); ok {
			return x.Results
		}
	}
	return nil
}

func (x *CommandResult) GetLog() *LogLines {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *CommandResult) GetCounters() *CounterData {
	if x != nil {
		if x, ok := x.Payload.(*CommandResult_Counters); ok {
			return x.Counters
		}
	}
	return nil
}

type isCommandResult_Payload interface {
	isCommandResult_Payload()
}

type CommandResult_List struct {
	List *ProcessList `protobuf:"bytes,10,opt,name=list,proto3,oneof"`
}

type CommandResult_Get struct {
	Get *GetResponse `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type CommandResult_Summary struct {
	Summary *Summary `protobuf:"bytes,12,opt,name=summary,proto3,oneof"`
}

type CommandResult_Results struct {
	Results *ActionResults `protobuf:"bytes,13,opt,name=results,proto3,oneof"`
}

type CommandResult_Log struct {
	Log *LogLines `protobuf:"bytes,14,opt,name=log,proto3,oneof"`
}

type CommandResult_Counters struct {
	Counters *CounterData `protobuf:"bytes,15,opt,name=counters,proto3,oneof"`
}

func (*CommandResult_List) isCommandResult_Payload() {}

func (*CommandResult_Get) isCommandResult_Payload() {}

func (*CommandResult_Summary) isCommandResult_Payload() {}

func (*CommandResult_Results) isCommandResult_Payload() {}

func (*CommandResult_Log) isCommandResult_Payload() {}

func (*CommandResult_Counters) isCommandResult_Payload() {}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_agentwire_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessList) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"` // Get returns nil for unknown services
	Info          *ProcessInfo           `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_agentwire_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetInfo() *ProcessInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type Summary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Running        int32                  `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Stopped        int32                  `protobuf:"varint,3,opt,name=stopped,proto3" json:"stopped,omitempty"`
	Failed         int32                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	TotalMemoryMb  int64                  `protobuf:"varint,5,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	FailedServices map[string]string      `protobuf:"bytes,6,rep,name=failed_services,json=failedServices,proto3" json:"failed_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // name -> lastError
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_agentwire_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Summary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *Summary) GetStopped() int32 {
	if x != nil {
		return x.Stopped
	}
	return 0
}

func (x *Summary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Summary) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *Summary) GetFailedServices() map[string]string {
	if x != nil {
		return x.FailedServices
	}
	return nil
}

type ActionResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ActionResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResults) Reset() {
	*x = ActionResults{}
	mi := &file_agentwire_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResults) ProtoMessage() {}

func (x *ActionResults) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResults.ProtoReflect.Descriptor instead.
func (*ActionResults) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ActionResults) GetResults() []*ActionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type LogLines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLines) Reset() {
	*x = LogLines{}
	mi := &file_agentwire_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLines) ProtoMessage() {}

func (x *LogLines) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLines.ProtoReflect.Descriptor instead.
func (*LogLines) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{21}
}

func (x *LogLines) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Display       string                 `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // cluster | gateway | infra
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Running       bool                   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,8,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,9,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	StartedAt     string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // RFC3339, empty when stopped
	RestartCount  int32                  `protobuf:"varint,11,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	Enabled       bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	LastError     string                 `protobuf:"bytes,14,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_agentwire_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *ProcessInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProcessInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProcessInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *ProcessInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ProcessInfo) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ProcessInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_agentwire_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ActionResult) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ActionResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CounterData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommitPosition int64                  `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	SnapshotCount  int64                  `protobuf:"varint,2,opt,name=snapshot_count,json=snapshotCount,proto3" json:"snapshot_count,omitempty"`
	NodeRole       int64                  `protobuf:"varint,3,opt,name=node_role,json=nodeRole,proto3" json:"node_role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CounterData) Reset() {
	*x = CounterData{}
	mi := &file_agentwire_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterData) ProtoMessage() {}

func (x *CounterData) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterData.ProtoReflect.Descriptor instead.
func (*CounterData) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{24}
}

func (x *CounterData) GetCommitPosition() int64 {
	if x != nil {
		return x.CommitPosition
	}
	return 0
}

func (x *CounterData) GetSnapshotCount() int64 {
	if x != nil {
		return x.SnapshotCount
	}
	return 0
}

func (x *CounterData) GetNodeRole() int64 {
	if x != nil {
		return x.NodeRole
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // started|stopped|crashed|cascade-stop|disarmed|adopted
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,5,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agentwire_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{25}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Event) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Event) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

type FetchArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchArtifactRequest) Reset() {
	*x = FetchArtifactRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchArtifactRequest) ProtoMessage() {}

func (x *FetchArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchArtifactRequest.ProtoReflect.Descriptor instead.
func (*FetchArtifactRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{26}
}

func (x *FetchArtifactRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type ArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunk) Reset() {
	*x = ArtifactChunk{}
	mi := &file_agentwire_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunk) ProtoMessage() {}

func (x *ArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunk.ProtoReflect.Descriptor instead.
func (*ArtifactChunk) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{27}
}

func (x *ArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agentwire_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{28}
}

func (x *EnrollRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *EnrollRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem  []byte                 `protobuf:"bytes,2,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	CaPem         []byte                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agentwire_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwire_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agentwire_agent_proto_rawDescGZIP(), []int{29}
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetClientKeyPem() []byte {
	if x != nil {
		return x.ClientKeyPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

var File_agentwire_agent_proto protoreflect.FileDescriptor

const file_agentwire_agent_proto_rawDesc = "" +
	"\n" +
	"\x15agentwire/agent.proto\x12\x15openexchange.agent.v1\"\x85\x02\n" +
	"\fAgentMessage\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.openexchange.agent.v1.HelloH\x00R\x05hello\x12B\n" +
	"\bsnapshot\x18\x02 \x01(\v2$.openexchange.agent.v1.StateSnapshotH\x00R\bsnapshot\x12>\n" +
	"\x06result\x18\x03 \x01(\v2$.openexchange.agent.v1.CommandResultH\x00R\x06result\x124\n" +
	"\x05event\x18\x04 \x01(\v2\x1c.openexchange.agent.v1.EventH\x00R\x05eventB\x05\n" +
	"\x03msg\"\x99\x01\n" +
	"\x0eControlMessage\x12>\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1f.openexchange.agent.v1.HelloAckH\x00R\bhelloAck\x12:\n" +
	"\acommand\x18\x02 \x01(\v2\x1e.openexchange.agent.v1.CommandH\x00R\acommandB\x05\n" +
	"\x03msgJ\x04\b\x03\x10\x04\"j\n" +
	"\x05Hello\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12#\n" +
	"\rproto_version\x18\x03 \x01(\rR\fprotoVersion\">\n" +
	"\bHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Q\n" +
	"\rStateSnapshot\x12@\n" +
	"\tprocesses\x18\x01 \x03(\v2\".openexchange.agent.v1.ProcessInfoR\tprocesses\"\xab\x05\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x128\n" +
	"\x04list\x18\n" +
	" \x01(\v2\".openexchange.agent.v1.ListRequestH\x00R\x04list\x125\n" +
	"\x03get\x18\v \x01(\v2!.openexchange.agent.v1.GetRequestH\x00R\x03get\x12A\n" +
	"\asummary\x18\f \x01(\v2%.openexchange.agent.v1.SummaryRequestH\x00R\asummary\x12;\n" +
	"\x05start\x18\r \x01(\v2#.openexchange.agent.v1.StartRequestH\x00R\x05start\x128\n" +
	"\x04stop\x18\x0e \x01(\v2\".openexchange.agent.v1.StopRequestH\x00R\x04stop\x12A\n" +
	"\arestart\x18\x0f \x01(\v2%.openexchange.agent.v1.RestartRequestH\x00R\arestart\x128\n" +
	"\x04bulk\x18\x10 \x01(\v2\".openexchange.agent.v1.BulkRequestH\x00R\x04bulk\x12B\n" +
	"\btail_log\x18\x11 \x01(\v2%.openexchange.agent.v1.TailLogRequestH\x00R\atailLog\x12Q\n" +
	"\rnode_counters\x18\x12 \x01(\v2*.openexchange.agent.v1.NodeCountersRequestH\x00R\fnodeCounters\x12I\n" +
	"\ainstall\x18\x13 \x01(\v2-.openexchange.agent.v1.InstallArtifactRequestH\x00R\ainstallB\x06\n" +
	"\x04verb\"\r\n" +
	"\vListRequest\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eSummaryRequest\"@\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tunchecked\x18\x02 \x01(\bR\tunchecked\"7\n" +
	"\vStopRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"$\n" +
	"\x0eRestartRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8c\x01\n" +
	"\vBulkRequest\x125\n" +
	"\x02op\x18\x01 \x01(\x0e2%.openexchange.agent.v1.BulkRequest.OpR\x02op\"F\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTART_ALL\x10\x01\x12\f\n" +
	"\bSTOP_ALL\x10\x02\x12\x0f\n" +
	"\vRESTART_ALL\x10\x03\"@\n" +
	"\x0eTailLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\".\n" +
	"\x13NodeCountersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\x96\x01\n" +
	"\x16InstallArtifactRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\xc9\x03\n" +
	"\rCommandResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12 \n" +
	"\vunsupported\x18\x03 \x01(\bR\vunsupported\x128\n" +
	"\x04list\x18\n" +
	" \x01(\v2\".openexchange.agent.v1.ProcessListH\x00R\x04list\x126\n" +
	"\x03get\x18\v \x01(\v2\".openexchange.agent.v1.GetResponseH\x00R\x03get\x12:\n" +
	"\asummary\x18\f \x01(\v2\x1e.openexchange.agent.v1.SummaryH\x00R\asummary\x12@\n" +
	"\aresults\x18\r \x01(\v2$.openexchange.agent.v1.ActionResultsH\x00R\aresults\x123\n" +
	"\x03log\x18\x0e \x01(\v2\x1f.openexchange.agent.v1.LogLinesH\x00R\x03log\x12@\n" +
	"\bcounters\x18\x0f \x01(\v2\".openexchange.agent.v1.CounterDataH\x00R\bcountersB\t\n" +
	"\apayload\"O\n" +
	"\vProcessList\x12@\n" +
	"\tprocesses\x18\x01 \x03(\v2\".openexchange.agent.v1.ProcessInfoR\tprocesses\"[\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x126\n" +
	"\x04info\x18\x02 \x01(\v2\".openexchange.agent.v1.ProcessInfoR\x04info\"\xb3\x02\n" +
	"\aSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\arunning\x18\x02 \x01(\x05R\arunning\x12\x18\n" +
	"\astopped\x18\x03 \x01(\x05R\astopped\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\x12&\n" +
	"\x0ftotal_memory_mb\x18\x05 \x01(\x03R\rtotalMemoryMb\x12[\n" +
	"\x0ffailed_services\x18\x06 \x03(\v22.openexchange.agent.v1.Summary.FailedServicesEntryR\x0efailedServices\x1aA\n" +
	"\x13FailedServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\rActionResults\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.openexchange.agent.v1.ActionResultR\aresults\" \n" +
	"\bLogLines\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"\x85\x03\n" +
	"\vProcessInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\b \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tuptime_ms\x18\t \x01(\x03R\buptimeMs\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12#\n" +
	"\rrestart_count\x18\v \x01(\x05R\frestartCount\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"last_error\x18\x0e \x01(\tR\tlastError\"p\n" +
	"\fActionResult\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"z\n" +
	"\vCounterData\x12'\n" +
	"\x0fcommit_position\x18\x01 \x01(\x03R\x0ecommitPosition\x12%\n" +
	"\x0esnapshot_count\x18\x02 \x01(\x03R\rsnapshotCount\x12\x1b\n" +
	"\tnode_role\x18\x03 \x01(\x03R\bnodeRole\"}\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x05 \x01(\x03R\batUnixMs\"7\n" +
	"\x14FetchArtifactRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"#\n" +
	"\rArtifactChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"G\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\"u\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x02 \x01(\fR\fclientKeyPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\fR\x05caPem2\xa6\x02\n" +
	"\fControlPlane\x12Y\n" +
	"\aSession\x12#.openexchange.agent.v1.AgentMessage\x1a%.openexchange.agent.v1.ControlMessage(\x010\x01\x12d\n" +
	"\rFetchArtifact\x12+.openexchange.agent.v1.FetchArtifactRequest\x1a$.openexchange.agent.v1.ArtifactChunk0\x01\x12U\n" +
	"\x06Enroll\x12$.openexchange.agent.v1.EnrollRequest\x1a%.openexchange.agent.v1.EnrollResponseB*Z(github.com/match/admin-gateway/agentwireb\x06proto3"

var (
	file_agentwire_agent_proto_rawDescOnce sync.Once
	file_agentwire_agent_proto_rawDescData []byte
)

func file_agentwire_agent_proto_rawDescGZIP() []byte {
	file_agentwire_agent_proto_rawDescOnce.Do(func() {
		file_agentwire_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentwire_agent_proto_rawDesc), len(file_agentwire_agent_proto_rawDesc)))
	})
	return file_agentwire_agent_proto_rawDescData
}

var file_agentwire_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agentwire_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_agentwire_agent_proto_goTypes = []any{
	(BulkRequest_Op)(0),            // 0: openexchange.agent.v1.BulkRequest.Op
	(*AgentMessage)(nil),           // 1: openexchange.agent.v1.AgentMessage
	(*ControlMessage)(nil),         // 2: openexchange.agent.v1.ControlMessage
	(*Hello)(nil),                  // 3: openexchange.agent.v1.Hello
	(*HelloAck)(nil),               // 4: openexchange.agent.v1.HelloAck
	(*StateSnapshot)(nil),          // 5: openexchange.agent.v1.StateSnapshot
	(*Command)(nil),                // 6: openexchange.agent.v1.Command
	(*ListRequest)(nil),            // 7: openexchange.agent.v1.ListRequest
	(*GetRequest)(nil),             // 8: openexchange.agent.v1.GetRequest
	(*SummaryRequest)(nil),         // 9: openexchange.agent.v1.SummaryRequest
	(*StartRequest)(nil),           // 10: openexchange.agent.v1.StartRequest
	(*StopRequest)(nil),            // 11: openexchange.agent.v1.StopRequest
	(*RestartRequest)(nil),         // 12: openexchange.agent.v1.RestartRequest
	(*BulkRequest)(nil),            // 13: openexchange.agent.v1.BulkRequest
	(*TailLogRequest)(nil),         // 14: openexchange.agent.v1.TailLogRequest
	(*NodeCountersRequest)(nil),    // 15: openexchange.agent.v1.NodeCountersRequest
	(*InstallArtifactRequest)(nil), // 16: openexchange.agent.v1.InstallArtifactRequest
	(*CommandResult)(nil),          // 17: openexchange.agent.v1.CommandResult
	(*ProcessList)(nil),            // 18: openexchange.agent.v1.ProcessList
	(*GetResponse)(nil),            // 19: openexchange.agent.v1.GetResponse
	(*Summary)(nil),                // 20: openexchange.agent.v1.Summary
	(*ActionResults)(nil),          // 21: openexchange.agent.v1.ActionResults
	(*LogLines)(nil),               // 22: openexchange.agent.v1.LogLines
	(*ProcessInfo)(nil),            // 23: openexchange.agent.v1.ProcessInfo
	(*ActionResult)(nil),           // 24: openexchange.agent.v1.ActionResult
	(*CounterData)(nil),            // 25: openexchange.agent.v1.CounterData
	(*Event)(nil),                  // 26: openexchange.agent.v1.Event
	(*FetchArtifactRequest)(nil),   // 27: openexchange.agent.v1.FetchArtifactRequest
	(*ArtifactChunk)(nil),          // 28: openexchange.agent.v1.ArtifactChunk
	(*EnrollRequest)(nil),          // 29: openexchange.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),         // 30: openexchange.agent.v1.EnrollResponse
	nil,                            // 31: openexchange.agent.v1.Summary.FailedServicesEntry
}
var file_agentwire_agent_proto_depIdxs = []int32{
	3,  // 0: openexchange.agent.v1.AgentMessage.hello:type_name -> openexchange.agent.v1.Hello
	5,  // 1: openexchange.agent.v1.AgentMessage.snapshot:type_name -> openexchange.agent.v1.StateSnapshot
	17, // 2: openexchange.agent.v1.AgentMessage.result:type_name -> openexchange.agent.v1.CommandResult
	26, // 3: openexchange.agent.v1.AgentMessage.event:type_name -> openexchange.agent.v1.Event
	4,  // 4: openexchange.agent.v1.ControlMessage.hello_ack:type_name -> openexchange.agent.v1.HelloAck
	6,  // 5: openexchange.agent.v1.ControlMessage.command:type_name -> openexchange.agent.v1.Command
	23, // 6: openexchange.agent.v1.StateSnapshot.processes:type_name -> openexchange.agent.v1.ProcessInfo
	7,  // 7: openexchange.agent.v1.Command.list:type_name -> openexchange.agent.v1.ListRequest
	8,  // 8: openexchange.agent.v1.Command.get:type_name -> openexchange.agent.v1.GetRequest
	9,  // 9: openexchange.agent.v1.Command.summary:type_name -> openexchange.agent.v1.SummaryRequest
	10, // 10: openexchange.agent.v1.Command.start:type_name -> openexchange.agent.v1.StartRequest
	11, // 11: openexchange.agent.v1.Command.stop:type_name -> openexchange.agent.v1.StopRequest
	12, // 12: openexchange.agent.v1.Command.restart:type_name -> openexchange.agent.v1.RestartRequest
	13, // 13: openexchange.agent.v1.Command.bulk:type_name -> openexchange.agent.v1.BulkRequest
	14, // 14: openexchange.agent.v1.Command.tail_log:type_name -> openexchange.agent.v1.TailLogRequest
	15, // 15: openexchange.agent.v1.Command.node_counters:type_name -> openexchange.agent.v1.NodeCountersRequest
	16, // 16: openexchange.agent.v1.Command.install:type_name -> openexchange.agent.v1.InstallArtifactRequest
	0,  // 17: openexchange.agent.v1.BulkRequest.op:type_name -> openexchange.agent.v1.BulkRequest.Op
	18, // 18: openexchange.agent.v1.CommandResult.list:type_name -> openexchange.agent.v1.ProcessList
	19, // 19: openexchange.agent.v1.CommandResult.get:type_name -> openexchange.agent.v1.GetResponse
	20, // 20: openexchange.agent.v1.CommandResult.summary:type_name -> openexchange.agent.v1.Summary
	21, // 21: openexchange.agent.v1.CommandResult.results:type_name -> openexchange.agent.v1.ActionResults
	22, // 22: openexchange.agent.v1.CommandResult.log:type_name -> openexchange.agent.v1.LogLines
	25, // 23: openexchange.agent.v1.CommandResult.counters:type_name -> openexchange.agent.v1.CounterData
	23, // 24: openexchange.agent.v1.ProcessList.processes:type_name -> openexchange.agent.v1.ProcessInfo
	23, // 25: openexchange.agent.v1.GetResponse.info:type_name -> openexchange.agent.v1.ProcessInfo
	31, // 26: openexchange.agent.v1.Summary.failed_services:type_name -> openexchange.agent.v1.Summary.FailedServicesEntry
	24, // 27: openexchange.agent.v1.ActionResults.results:type_name -> openexchange.agent.v1.ActionResult
	1,  // 28: openexchange.agent.v1.ControlPlane.Session:input_type -> openexchange.agent.v1.AgentMessage
	27, // 29: openexchange.agent.v1.ControlPlane.FetchArtifact:input_type -> openexchange.agent.v1.FetchArtifactRequest
	29, // 30: openexchange.agent.v1.ControlPlane.Enroll:input_type -> openexchange.agent.v1.EnrollRequest
	2,  // 31: openexchange.agent.v1.ControlPlane.Session:output_type -> openexchange.agent.v1.ControlMessage
	28, // 32: openexchange.agent.v1.ControlPlane.FetchArtifact:output_type -> openexchange.agent.v1.ArtifactChunk
	30, // 33: openexchange.agent.v1.ControlPlane.Enroll:output_type -> openexchange.agent.v1.EnrollResponse
	31, // [31:34] is the sub-list for method output_type
	28, // [28:31] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_agentwire_agent_proto_init() }
func file_agentwire_agent_proto_init() {
	if File_agentwire_agent_proto != nil {
		return
	}
	file_agentwire_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Snapshot)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Event)(nil),
	}
	file_agentwire_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlMessage_HelloAck)(nil),
		(*ControlMessage_Command)(nil),
	}
	file_agentwire_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*Command_List)(nil),
		(*Command_Get)(nil),
		(*Command_Summary)(nil),
		(*Command_Start)(nil),
		(*Command_Stop)(nil),
		(*Command_Restart)(nil),
		(*Command_Bulk)(nil),
		(*Command_TailLog)(nil),
		(*Command_NodeCounters)(nil),
		(*Command_Install)(nil),
	}
	file_agentwire_agent_proto_msgTypes[16].OneofWrappers = []any{
		(*CommandResult_List)(nil),
		(*CommandResult_Get)(nil),
		(*CommandResult_Summary)(nil),
		(*CommandResult_Results)(nil),
		(*CommandResult_Log)(nil),
		(*CommandResult_Counters)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentwire_agent_proto_rawDesc), len(file_agentwire_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentwire_agent_proto_goTypes,
		DependencyIndexes: file_agentwire_agent_proto_depIdxs,
		EnumInfos:         file_agentwire_agent_proto_enumTypes,
		MessageInfos:      file_agentwire_agent_proto_msgTypes,
	}.Build()
	File_agentwire_agent_proto = out.File
	file_agentwire_agent_proto_goTypes = nil
	file_agentwire_agent_proto_depIdxs = nil
}
